name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: GET Method
      id: get-method
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: GET Method
        setup-command: pip install fastapi uvicorn pydantic pytest httpx
        command: pytest tests/test_get_person.py
        timeout: 10
        max-score: 10
    - name: POST Method
      id: post-method
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: POST Method
        setup-command: pip install fastapi uvicorn pydantic pytest httpx
        command: pytest tests/test_post_person.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GET-METHOD_RESULTS: "${{steps.get-method.outputs.result}}"
        POST-METHOD_RESULTS: "${{steps.post-method.outputs.result}}"
      with:
        runners: get-method,post-method
